version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca-app
    expose:
      - "8080"
    volumes:
      - C:\.gradle:/root/.gradle
    networks:
      - appnet

  nginx:
    image: nginx:latest
    container_name: biblioteca-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
